# Generated by Django 3.1.7 on 2021-05-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='coverImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.file'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('SCI-FI', 'Sci-fi'), ('DRAMA', 'Drama'), ('THRILLER', 'Thriller'), ('HORROR', 'Horror'), ('COMEDY', 'Comedy'), ('ACTION', 'Action')], default='ACTION', max_length=8),
        ),
    ]
