# Generated by Django 3.1.7 on 2021-05-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20210525_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='number_of_views',
            field=models.IntegerField(default=0),
        ),
    ]
