# Generated by Django 3.1.7 on 2021-05-26 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_movie_number_of_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='number_of_views',
            new_name='num_of_views',
        ),
    ]
