# Generated by Django 3.1.7 on 2021-06-02 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_movie_watch_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='coverImage',
            new_name='cover_image',
        ),
    ]
